CREATE TABLE Users (
    user_id        VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
    username       VARCHAR2(64) NOT NULL,
    password_hash  VARCHAR2(255) NOT NULL,
    role_code      VARCHAR2(32) DEFAULT 'STAFF' NOT NULL,
    is_active      NUMBER(1) DEFAULT 1 NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT ck_users_active CHECK (is_active IN (0, 1))
);

CREATE TABLE SKU (
    sku_id      VARCHAR2(64) NOT NULL,
    sku_name    VARCHAR2(128) NOT NULL,
    category    VARCHAR2(64),
    unit        VARCHAR2(16) DEFAULT 'PCS' NOT NULL,
    is_active   NUMBER(1) DEFAULT 1 NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_sku PRIMARY KEY (sku_id),
    CONSTRAINT ck_sku_active CHECK (is_active IN (0, 1))
);

CREATE TABLE Inventory (
    warehouse_id  VARCHAR2(36) DEFAULT 'DEFAULT' NOT NULL,
    sku_id        VARCHAR2(64) NOT NULL,
    quantity      NUMBER(18) DEFAULT 0 NOT NULL,
    updated_by    VARCHAR2(36),
    updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_inventory PRIMARY KEY (warehouse_id, sku_id),
    CONSTRAINT fk_inventory_sku FOREIGN KEY (sku_id) REFERENCES SKU (sku_id),
    CONSTRAINT fk_inventory_user FOREIGN KEY (updated_by) REFERENCES Users (user_id),
    CONSTRAINT ck_inventory_quantity CHECK (quantity >= 0)
);

CREATE TABLE Inbound_Orders (
    inbound_id    VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL,
    warehouse_id  VARCHAR2(36) DEFAULT 'DEFAULT' NOT NULL,
    sku_id        VARCHAR2(64) NOT NULL,
    quantity      NUMBER(18) NOT NULL,
    status        VARCHAR2(20) DEFAULT 'COMPLETED' NOT NULL,
    operator_id   VARCHAR2(36),
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_inbound_orders PRIMARY KEY (inbound_id),
    CONSTRAINT fk_inbound_sku FOREIGN KEY (sku_id) REFERENCES SKU (sku_id),
    CONSTRAINT fk_inbound_user FOREIGN KEY (operator_id) REFERENCES Users (user_id),
    CONSTRAINT ck_inbound_quantity CHECK (quantity > 0),
    CONSTRAINT ck_inbound_status CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE Audit_Logs (
    audit_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    warehouse_id  VARCHAR2(36) NOT NULL,
    sku_id        VARCHAR2(64) NOT NULL,
    action_type   VARCHAR2(16) NOT NULL,
    old_quantity  NUMBER(18),
    new_quantity  NUMBER(18) NOT NULL,
    changed_by    VARCHAR2(36),
    changed_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (audit_id),
    CONSTRAINT fk_audit_inventory FOREIGN KEY (warehouse_id, sku_id)
        REFERENCES Inventory (warehouse_id, sku_id),
    CONSTRAINT ck_audit_action CHECK (action_type IN ('INSERT', 'UPDATE'))
);

CREATE INDEX idx_inventory_sku ON Inventory (sku_id);
CREATE INDEX idx_inbound_created_at ON Inbound_Orders (created_at);
CREATE INDEX idx_audit_sku_changed_at ON Audit_Logs (sku_id, changed_at);
